Reduce gif size
easystats/datawizard pull request #192
Opened 2022-07-05 08:26 UTC by etiennebacher

Close #188. @DominiqueMakowski feel free to modify as you want, for now it looks like this:

![image](https://user-images.githubusercontent.com/52219252/177284508-a99ce0b9-0aad-41e6-a297-da4e5d538d3f.png)

2022-07-05 08:29 UTC, etiennebacher commented on README.Rmd
> +***:sparkles: Hockety pockety wockety wack, prepare this data forth and back***
ah ok I wasn't sure if you wanted to include it :sweat_smile:

2022-07-05 08:31 UTC, etiennebacher commented on README.Rmd
> +***:sparkles: Hockety pockety wockety wack, prepare this data forth and back***
but you want to keep the gif, right?

2022-07-05 14:10 UTC, IndrajeetPatil commented
I am really not sure about having that poem upfront, or even having it in the README at all.

I'd also like for other weight in on this.

2022-07-06 20:43 UTC, strengejacke commented
> I think the poem is a little confusing...

It's a "rime richissime".

2022-07-07 10:05 UTC, etiennebacher commented
what about the gif?

2022-07-07 17:42 UTC, bwiernik requested changes

2022-07-07 17:42 UTC, bwiernik commented on README.Rmd
> +Here comes `datawizard`, a lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It is part of the [easystats ecosystem](https://easystats.github.io/blog/),
```suggestion
`datawizard` is a lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It is part of the [easystats ecosystem](https://easystats.github.io/blog/), a suite of R packages to deal with your entire statistical analysis, from cleaning the data to reporting the results.

Most courses and tutorials about statistical modeling focus assume that you are working with a clean and tidy dataset. In practice, however, a major part of doing statistical modeling is preparing your data--cleaning up values, creating new columns, reshaping the dataset, or transforming some variables. `datawizard` provides easy to use tools to perform these common, critical, and sometimes tedious data preparation tasks. 
```

2022-07-08 06:47 UTC, etiennebacher commented on README.Rmd
> +Here comes `datawizard`, a lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It is part of the [easystats ecosystem](https://easystats.github.io/blog/),
done

2022-07-08 06:50 UTC, IndrajeetPatil requested changes

2022-07-08 06:50 UTC, IndrajeetPatil commented on README.Rmd
> +`datawizard` is a lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It is part of the [easystats ecosystem](https://easystats.github.io/blog/), a suite o
```suggestion
`{datawizard}` is a lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It is part of the [easystats ecosystem](https://easystats.github.io/blog/), a suite of R packages to deal with your entire statistical analysis, from cleaning the data to reporting the results.
```

2022-07-08 06:50 UTC, IndrajeetPatil commented on README.Rmd
> +`datawizard` is a lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It is part of the [easystats ecosystem](https://easystats.github.io/blog/), a suite o
```suggestion
`datawizard` is a lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It is part of the [easystats ecosystem](https://easystats.github.io/easystats/), a suite of R packages to deal with your entire statistical analysis, from cleaning the data to reporting the results.
```

2022-07-08 06:53 UTC, etiennebacher commented on README.Rmd
> +`datawizard` is a lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It is part of the [easystats ecosystem](https://easystats.github.io/blog/), a suite o
done

2022-07-08 06:55 UTC, IndrajeetPatil approved these changes
Thanks!

2022-07-08 09:06 UTC, merged