Mean sd
easystats/datawizard pull request #348
Opened 2023-01-10 13:37 UTC by mattansb

I always write a function for computing the mean+-sd, and I just WANT IT TO EXIST SOMEWHERE!

What do you think?

``` r
library(datawizard)

mean_sd(mtcars$mpg)
#>      -SD     Mean      +SD 
#> 14.06368 20.09062 26.11757

median_mad(mtcars$mpg)
#>     -MAD   Median     +MAD 
#> 13.78851 19.20000 24.61149
```

<sup>Created on 2023-01-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2023-01-10 14:29 UTC, strengejacke commented on R/mean_sd.R
> +
`stats::sd`

2023-01-10 14:29 UTC, strengejacke commented on R/mean_sd.R
> +
`stats::median`, `stats::mad`.

2023-01-10 14:44 UTC, strengejacke commented
``` r
centrality_dispersion <- function(x,
                                  type = "mean",
                                  na.rm = TRUE,
                                  times = 1,
                                  constant = 1.4,
                                  named = TRUE,
                                  ...) {
  x <- as.numeric(x)
  type <- match.arg(type, choices = c("mean", "median"))

  # centrality
  M <- switch(type,
    median = stats::median(x, na.rm = na.rm),
    mean(x, na.rm = na.rm)
  )

  S <- switch(type,
    median = stats::mad(x, na.rm = na.rm, constant = constant),
    stats::sd(x, na.rm = na.rm)
  )
  
  v <- M + c(-rev(seq_len(times)), 0, seq_len(times)) * S
  
  if (isTRUE(named)) {
     string_cs <- switch(type,
      median = c("Median", "MAD"),
      c("Mean", "SD")
    )
    names(v) <- c(
      paste0("-", rev(seq_len(times)), " ", string_cs[2]),
      string_cs[1],
      paste0("+", seq_len(times), " ", string_cs[2])
    )
  }
  v
}

mean_sd <- function(x, na.rm = TRUE, times = 1, named = TRUE, ...) {
  centrality_dispersion(x, type = "mean", na.rm = na.rm, times = times, named = named, ...)
}

median_mad <- function(x, na.rm = TRUE, times = 1, constant = 1.4, named = TRUE, ...) {
  centrality_dispersion(x, type = "median", na.rm = na.rm, times = times, constant = constant, named = named, ...)
}

centrality_dispersion(mtcars$mpg)
#>    -1 SD     Mean    +1 SD 
#> 14.06368 20.09062 26.11757
centrality_dispersion(mtcars$mpg, times = 3)
#>     -3 SD     -2 SD     -1 SD      Mean     +1 SD     +2 SD     +3 SD 
#>  2.009781  8.036729 14.063677 20.090625 26.117573 32.144521 38.171469
centrality_dispersion(mtcars$mpg, type = "median", times = 2)
#> -2 MAD -1 MAD Median +1 MAD +2 MAD 
#>   8.98  14.09  19.20  24.31  29.42

mean_sd(mtcars$mpg)
#>    -1 SD     Mean    +1 SD 
#> 14.06368 20.09062 26.11757

median_mad(mtcars$mpg, times = 2)
#> -2 MAD -1 MAD Median +1 MAD +2 MAD 
#>   8.98  14.09  19.20  24.31  29.42
```

<sup>Created on 2023-01-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2023-01-10 16:38 UTC, mattansb commented
I don't see a need for a "generic" - calling it would be more complicated than calling the right function.

Also, have you ever needed `times > 1`?

2023-01-10 19:19 UTC, strengejacke commented
> I don't see a need for a "generic" - calling it would be more complicated than calling the right function.

We can make it internal, so we avoid repeated code.

> 
> Also, have you ever needed `times > 1`?

Maybe not me, but I bet you'll find a user who needs it 😉

2023-01-11 09:18 UTC, mattansb commented
This can be merged - all failing tests are unrelated to this PR.

2023-01-11 20:52 UTC, etiennebacher requested changes
Thanks, can you also add tests for these two functions?

2023-01-11 20:53 UTC, etiennebacher commented on NEWS.md
> +# datawizard 0.6.5.xx
can you also bump the version in DESCRIPTION?

2023-01-13 11:31 UTC, mattansb commented on R/mean_sd.R
> +#' @param ... Not used.
I find it to be a general good practice, but we can drop it if you want.

2023-01-13 11:54 UTC, etiennebacher commented on tests/testthat/test-mean_sd.R
> +  expect_equal(names(msd), c("-SD", "Mean", "+SD"))
you can use `expect_named()` instead (which is better according to `lintr`)

2023-01-13 15:49 UTC, strengejacke commented on R/mean_sd.R
> +#' @param ... Not used.
You could have a use for `...` when passing arguments down to other functions, even if your function is no generic.

2023-01-14 10:01 UTC, etiennebacher approved these changes

2023-01-14 10:01 UTC, merged

2023-01-14 10:02 UTC, etiennebacher commented
Thanks @mattansb!