Remove re-exports
easystats/datawizard pull request #398
Opened 2023-03-29 17:48 UTC by IndrajeetPatil

cf. https://github.com/easystats/easystats/issues/292

2023-03-29 18:40 UTC, IndrajeetPatil commented
Needs to wait for _parameters_ release.

2023-04-06 06:21 UTC, IndrajeetPatil commented
@etiennebacher This should be ready for a review now since _parameters_ update is now on CRAN.

2023-04-06 08:39 UTC, etiennebacher requested changes

2023-04-06 08:39 UTC, etiennebacher commented on DESCRIPTION
> +    easystats/parameters
do we need this now that parameters is on CRAN?

2023-04-06 09:23 UTC, etiennebacher approved these changes

2023-04-06 09:23 UTC, merged

2023-04-06 09:24 UTC, etiennebacher commented
Thanks @IndrajeetPatil